# -*- coding: utf-8 -*-
"""Dataviz Gennaro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-pAnN-T54ieNBrYgs6qb1npD_VNx5sZn

# Pre Processing o preparazione df
"""

import pandas as pd
import os
from standardize import robust_standardize_excel

# Detect file location robustly
file_path = 'Anziani del Comune di Pisa 1370-1392.xlsx'
if not os.path.exists(file_path):
    file_path = os.path.join('..', 'Anziani del Comune di Pisa 1370-1392.xlsx')
if not os.path.exists(file_path):
    file_path = r"c:\Users\diesi\Documents\progetti - Python\data viz Gennaro\Anziani del Comune di Pisa 1370-1392.xlsx"

print(f"Loading and standardizing Excel from: {file_path}")
total_df = robust_standardize_excel(file_path)

total_df.to_csv('total_df.csv', index=False)
total_df.to_excel('total_df.xlsx', index=False)
print("DataFrame saved to 'total_df.csv' and 'total_df.xlsx'")

anziani_1 = total_df[total_df['ruolo']=='anziano #1']
anziani_1['altra nota'].describe()
anziani_1['altra nota'].value_counts()

"""# Post-processing/analisi"""

import pandas as pd

# Load total_df (1).csv with path fallback
csv_path = 'total_df (1).csv'
if not os.path.exists(csv_path):
    csv_path = os.path.join('..', 'total_df (1).csv')
if not os.path.exists(csv_path):
    csv_path = 'total_df.csv'

print(f"Loading data for post-processing analysis from: {csv_path}")
df = pd.read_csv(csv_path)
df

df.describe()



"""# Task
To prepare the DataFrame for analysis, rename the 'nota' column to 'Famiglia' and 'altra nota' to 'Professione'. Then, filter the DataFrame to include only rows where the 'ruolo' indicates an 'anziano', creating a new DataFrame `anziani_df` focused on the Anziani.

## Prepara DataFrame per l'analisi

### Subtask:
Rinomina la colonna 'nota' in 'Famiglia' e 'altra nota' in 'Professione' nel dataframe. Successivamente, filtra il dataframe per includere solo le righe dove il 'ruolo' indica un 'anziano', creando un nuovo dataframe focalizzato sugli Anziani.

**Reasoning**:
The subtask requires renaming specific columns in the DataFrame `df` and then filtering it to create a new DataFrame `anziani_df` containing only rows where the 'ruolo' column indicates an 'anziano'.
"""

df = df.rename(columns={'nota': 'Famiglia', 'altra nota': 'Professione'})
anziani_df = df #df[df['ruolo'].str.contains('anziano', na=False)]
print(f"DataFrame 'df' after renaming columns:")
print(df.head())
print(f"\nNew DataFrame 'anziani_df' with {len(anziani_df)} rows:")
print(anziani_df.head())

"""## Analisi della Rappresentazione Familiare (Periodo Complessivo)

### Subtask:
Calcola la frequenza di ogni nome di famiglia unico ('Famiglia') all'interno del dataframe filtrato ('anziani_df') per l'intero periodo (1368-1392). Identifica e visualizza le 10 famiglie più rappresentate.

**Reasoning**:
To identify the most represented families, I will calculate the frequency of each unique family name in the 'Famiglia' column of the `anziani_df` DataFrame, excluding NaN values, and then select the top 10.
"""

family_counts = anziani_df['Famiglia'].value_counts().dropna()
top_10_families = family_counts.head(10)
print("Top 10 most represented families:")
print(top_10_families)

"""## Analisi della Rappresentazione Familiare (Decennio Specifico)

### Subtask:
Filtra il dataframe 'anziani_df' per un decennio specifico (ad esempio, 1370-1379, basandosi sulla colonna 'anno'). Calcola la frequenza di ogni nome di famiglia unico ('Famiglia') all'interno di questo decennio. Identifica e visualizza le 5 famiglie più rappresentate per questo decennio.

**Reasoning**:
To filter the DataFrame for the 1370-1379 decade, I need to first extract the start year from the 'anno' column, handling both single year and year range formats. Then, I'll use this extracted year to filter the `anziani_df` to create `anziani_df_1370s`.
"""

anziani_df['start_year'] = anziani_df['anno'].apply(lambda x: int(str(x).split('-')[0]))

anziani_df_1370s = anziani_df[(anziani_df['start_year'] >= 1370) & (anziani_df['start_year'] <= 1379)]

family_counts_1370s = anziani_df_1370s['Famiglia'].value_counts().dropna()
top_5_families_1370s = family_counts_1370s.head(5)

print("Top 5 most represented families for the 1370-1379 decade:")
print(top_5_families_1370s)

"""**Reasoning**:
The previous code generated a `SettingWithCopyWarning` because of modifying a slice of a DataFrame. To avoid this, I will explicitly create a copy of the `anziani_df` before adding the `start_year` column.


"""

anziani_df_copy = anziani_df.copy()
anziani_df_copy['start_year'] = anziani_df_copy['anno'].apply(lambda x: int(str(x).split('-')[0]))

anziani_df_1370s = anziani_df_copy[(anziani_df_copy['start_year'] >= 1370) & (anziani_df_copy['start_year'] <= 1379)]

family_counts_1370s = anziani_df_1370s['Famiglia'].value_counts().dropna()
top_5_families_1370s = family_counts_1370s.head(5)

print("Top 5 most represented families for the 1370-1379 decade:")
print(top_5_families_1370s)

"""## Analisi della Rappresentazione Professionale

### Subtask:
Calcola la frequenza di ogni professione unica ('Professione') all'interno del dataframe filtrato 'anziani_df'. Identifica e visualizza le 10 professioni più prevalenti. Crea un grafico a barre per visualizzare la distribuzione delle professioni più comuni.

**Reasoning**:
To analyze the professional representation, I will first calculate the frequency of each unique profession in the 'Professione' column of `anziani_df`, excluding NaN values, and then extract the top 10 most prevalent professions.
"""

profession_counts = anziani_df['Professione'].value_counts().dropna()
top_10_professions = profession_counts.head(10)
print("Top 10 most prevalent professions among Anziani:")
print(top_10_professions)

"""**Reasoning**:
To visualize the distribution of the top 10 professions, I will use `matplotlib.pyplot` to create a bar chart, add appropriate labels and a title, and then display the plot.


"""

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))
top_10_professions.plot(kind='bar', color='skyblue')
plt.title('Top 10 Professioni degli Anziani')
plt.xlabel('Professione')
plt.ylabel('Frequenza')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""## Final Task

### Subtask:
Fornisci un riepilogo dell'analisi, includendo le osservazioni sulla rappresentazione familiare in diversi periodi e la prevalenza delle categorie professionali tra gli Anziani.

## Summary:

### Q&A
The analysis provided observations on family representation across different periods and the prevalence of professional categories among the Anziani.

### Data Analysis Key Findings
*   The initial dataset was prepared by renaming the 'nota' column to 'Famiglia' and 'altra nota' to 'Professione'.
*   A filtered DataFrame, `anziani_df`, was created, containing 1112 entries specifically for individuals identified as 'anziano'.
*   Over the entire period (1368-1392), the 'de Cascina' family was the most represented among the Anziani with 17 occurrences, followed by 'Astarii', 'Alliata', and 'Bandini' each with 12 occurrences.
*   For the specific decade of 1370-1379, the 'Bertaloctus' family was the most represented with 11 occurrences, followed by 'Bandini' (8), 'de Cascina' (7), 'Astarii' (6), and 'Bondiei' (5).
*   Among the Anziani, 'Notarius' was the most prevalent profession with 122 occurrences, followed by 'Vinarius' (97) and 'Tabernarius' (56).

### Insights or Next Steps
*   Investigate the socio-economic factors that might have contributed to the prominence of certain families and professions among the Anziani during these specific periods.
*   Conduct a comparative analysis of family and professional representation across different roles within the dataset, not just 'anziano', to understand broader societal structures.

# Task
**Analisi della Distribuzione delle Cariche per le Famiglie Principali**: Basandosi sulle famiglie più rappresentate identificate nel periodo complessivo (utilizzando il dataframe che include tutti i ruoli), calcola la distribuzione delle diverse cariche ('ruolo' come 'anziano', 'priore', 'canc. maior', 'notaio anziani') che queste famiglie hanno ricoperto. Visualizza i risultati in una tabella o un grafico.

## Analisi della Distribuzione delle Cariche per le Famiglie Principali

### Subtask:
Calculate the distribution of roles ('ruolo') held by the most represented families across all roles in the DataFrame `df`, and visualize the results.

**Reasoning**:
First, I'll extract the family names from the `top_10_families` Series to use them for filtering the main DataFrame.
"""

top_families_list = top_10_families.index.tolist()
print("List of top 10 families:", top_families_list)

"""**Reasoning**:
Now that the list of top families is available, I will filter the main DataFrame `df` to include only these families and then group by 'Famiglia' and 'ruolo' to count the occurrences of each role per family. This will allow us to see the distribution of roles within these prominent families.


"""

filtered_df_families = df[df['Famiglia'].isin(top_families_list)]
role_distribution = filtered_df_families.groupby(['Famiglia', 'ruolo']).size().unstack(fill_value=0)
print("Role distribution for top families:\n", role_distribution)

"""**Reasoning**:
To visualize the distribution of roles for each top family, I will create a stacked bar chart using the `role_distribution` DataFrame. This will clearly show how different roles are distributed across the most represented families.


"""

import matplotlib.pyplot as plt

plt.figure(figsize=(14, 8))
role_distribution.plot(kind='bar', stacked=True, cmap='viridis', ax=plt.gca())
plt.title('Distribuzione delle Cariche per le Famiglie Principali')
plt.xlabel('Famiglia')
plt.ylabel('Numero di Cariche')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Ruolo')
plt.tight_layout()
plt.show()

"""## Generazione Knowledge Base

### Subtask:
Compila un documento onnicomprensivo che riassuma tutte le analisi effettuate: rappresentazione familiare (generale e per decennio), prevalenza professionale e distribuzione delle cariche per le famiglie principali. Questo documento sarà strutturato come una knowledge base interrogabile con un chatbot.

## Knowledge Base: Analisi delle Cariche Politiche a Pisa (1369-1392)

Questo documento riassume le principali osservazioni e dati estratti dall'analisi delle cariche politiche a Pisa tra il 1369 e il 1392, con un focus sulla rappresentazione familiare, professionale e la distribuzione dei ruoli.

### 1. Rappresentazione Familiare Generale (1369-1392)

L'analisi della rappresentazione familiare complessiva tra tutti i ruoli (priore, anziano, notaio, cancelliere) ha rivelato la predominanza di alcune famiglie nel periodo tra il 1369 e il 1392. La seguente tabella mostra le 10 famiglie più rappresentate, basata sulla frequenza di apparizione nel dataset:

| Famiglia         | Frequenza |
| :--------------- | :-------- |
| Da San Casciano  | 40        |
| Alliata          | 32        |
| de Cascina       | 29        |
| de Vico          | 27        |
| Astarii          | 25        |
| de Campo         | 24        |
| Bonconti         | 21        |
| Murcius          | 18        |
| Griffi           | 18        |
| Grassus          | 17        |

Si osserva che la famiglia 'Da San Casciano' è stata la più presente, seguita da 'Alliata' e 'de Cascina'.

### 2. Rappresentazione Familiare per il Decennio 1370-1379

Focalizzando l'attenzione sul decennio specifico 1370-1379, la composizione delle famiglie più rappresentate tra gli 'Anziani' mostra alcune differenze. Le 5 famiglie più rappresentate in questo periodo sono:

| Famiglia         | Frequenza |
| :--------------- | :-------- |
| Da San Casciano  | 16        |
| Bonconti         | 14        |
| de Vico          | 13        |
| de Cascina       | 12        |
| Bertaloctus      | 12        |

In questo decennio, 'Da San Casciano' mantiene una forte presenza, con 'Bonconti' e 'de Vico' che emergono come attori significativi.

### 3. Prevalenza Professionale tra gli Anziani

L'analisi delle professioni tra gli 'Anziani' ha identificato diverse categorie professionali prevalenti. Le 10 professioni più comuni sono:

| Professione                      | Frequenza |
| :------------------------------- | :-------- |
| Notarius                         | 123       |
| Vinarius                         | 97        |
| Tabernarius                      | 56        |
| Coriarius                        | 48        |
| Mercante-Banchiere (Poloni 2017) | 43        |
| Pelliparius                      | 41        |
| Calthularius                     | 40        |
| Aurifex                          | 27        |
| Faber                            | 26        |
| Spetiarius                       | 21        |

Il 'Notarius' è di gran lunga la professione più rappresentata, suggerendo l'importanza dei notai nella gestione pubblica dell'epoca, seguito da 'Vinarius' e 'Tabernarius'.

### 4. Distribuzione delle Cariche per le Famiglie Principali

La distribuzione delle cariche ('ruolo') tra le famiglie più rappresentate (come identificate nell'analisi generale) fornisce un quadro più dettagliato della loro influenza. La tabella seguente illustra come le cariche di 'anziano #1', 'anziano #2', 'canc. maior', 'notaio anziani' e 'priore' si distribuiscono tra queste famiglie. Il grafico a barre generato in precedenza visualizza questa distribuzione in modo più intuitivo.

| Famiglia         | anziano #1 | anziano #2 | canc. maior | notaio anziani | priore |
| :--------------- | :--------- | :--------- | :---------- | :------------- | :----- |
| Alliata          | 12         | 0          | 0           | 0              | 20     |
| Astarii          | 12         | 0          | 0           | 0              | 13     |
| Bonconti         | 6          | 0          | 0           | 0              | 15     |
| Da San Casciano  | 8          | 2          | 0           | 6              | 24     |
| Grassus          | 5          | 0          | 0           | 0              | 12     |
| Griffi           | 4          | 0          | 0           | 0              | 14     |
| Murcius          | 4          | 0          | 0           | 0              | 14     |
| de Campo         | 3          | 6          | 6           | 3              | 6      |
| de Cascina       | 13         | 4          | 3           | 4              | 5      |
| de Vico          | 5          | 4          | 0           | 6              | 12     |

**Osservazioni chiave dalla distribuzione delle cariche:**

*   **Famiglie Dominanti in un Ruolo:** Famiglie come 'Alliata' e 'Bonconti' mostrano una forte inclinazione verso il ruolo di 'priore', mentre 'Astarii' ha una presenza equilibrata tra 'anziano #1' e 'priore'.
*   **Diversificazione dei Ruoli:** 'Da San Casciano' è ben rappresentata in più ruoli, inclusi 'notaio anziani' e 'priore', indicando una partecipazione più diversificata nella vita pubblica. Anche 'de Campo' e 'de Cascina' mostrano una distribuzione dei ruoli più ampia, includendo 'canc. maior' e 'notaio anziani'.
*   **Concentrazione su Anziano:** Famiglie come 'de Cascina' e 'Astarii' hanno un numero significativo di 'anziano #1'.

Queste analisi forniscono una base per comprendere le dinamiche socio-politiche di Pisa in questo periodo storico, evidenziando il potere e l'influenza di specifiche famiglie e categorie professionali nella gestione della città.

## Final Task

### Subtask:
Fornisci un riepilogo dell'analisi completa, pronta per essere utilizzata come knowledge base.

## Summary:

### Data Analysis Key Findings

*   **Overall Family Representation (1369-1392)**: The analysis of political offices in Pisa revealed that 'Da San Casciano' was the most represented family with 40 occurrences, followed by 'Alliata' (32) and 'de Cascina' (29) across all roles (priore, anziano, notaio, cancelliere).
*   **Decade-Specific Family Representation (1370-1379)**: For the decade 1370-1379, 'Da San Casciano' maintained its dominance among the 'Anziani' with 16 occurrences, followed by 'Bonconti' (14) and 'de Vico' (13).
*   **Professional Prevalence Among 'Anziani'**: Among the 'Anziani', 'Notarius' was the most common profession by a significant margin, with 123 occurrences. Other prevalent professions included 'Vinarius' (97) and 'Tabernarius' (56).
*   **Role Distribution Among Principal Families**:
    *   Families like 'Alliata' (20 priore, 12 anziano \#1) and 'Bonconti' (15 priore, 6 anziano \#1) showed a strong inclination towards the 'priore' role.
    *   'Da San Casciano' exhibited a diversified participation across roles, with 24 'priore', 8 'anziano \#1', 2 'anziano \#2', and 6 'notaio anziani'.
    *   'de Campo' and 'de Cascina' also demonstrated broader role distribution, including 'canc. maior' and 'notaio anziani', beyond just 'anziano' and 'priore'.
    *   'de Cascina' (13 'anziano \#1') and 'Astarii' (12 'anziano \#1') had significant numbers in the 'anziano \#1' role.

### Insights or Next Steps

*   The findings highlight a clear power structure in Pisan politics, where certain families, such as 'Da San Casciano' and 'Alliata', consistently held significant influence, often diversifying their roles or specializing in high-ranking positions like 'priore'.
*   This comprehensive knowledge base can now be integrated with a chatbot to enable easy querying and retrieval of historical information regarding family representation, professional prevalence, and the distribution of political offices in Pisa during the specified period.
"""



"""# Task
Create a comprehensive knowledge base summarizing the family representation (general and by decade), professional prevalence, and distribution of roles for the main families from the provided data. Then, export this knowledge base to a markdown file named `knowledge_base.md`.

## Generazione Knowledge Base Completa

### Subtask:
Compila un documento onnicomprensivo che riassuma tutte le analisi effettuate: rappresentazione familiare (generale e per decennio), prevalenza professionale e distribuzione delle cariche per le famiglie principali. Questo documento sarà strutturato come una knowledge base interrogabile con un chatbot.

**Reasoning**:
I need to construct the markdown content for the 'Rappresentazione Familiare Generale (1369-1392)' section using the `top_10_families` Series and format it as a markdown table. Then, I will construct the markdown content for the 'Rappresentazione Familiare per il Decennio 1370-1379' section using the `top_5_families_1370s` Series, also formatted as a markdown table. Following that, I will construct the markdown content for the 'Prevalenza Professionale tra gli Anziani' section using the `top_10_professions` Series, formatted as a markdown table. Lastly, I will convert the `role_distribution` DataFrame into a markdown table for the 'Distribuzione delle Cariche per le Famiglie Principali' section and add key observations about the role distribution. Finally, I will combine all these markdown sections, along with introductory and concluding remarks, into a single comprehensive markdown string and store it in the `knowledge_base_content` variable.
"""

kb_intro = """## Knowledge Base: Analisi delle Cariche Politiche a Pisa (1369-1392)\n\nQuesto documento riassume le principali osservazioni e dati estratti dall'analisi delle cariche politiche a Pisa tra il 1369 e il 1392, con un focus sulla rappresentazione familiare, professionale e la distribuzione dei ruoli.\n"""

# 1. Rappresentazione Familiare Generale (1369-1392)
gen_family_section = """### 1. Rappresentazione Familiare Generale (1369-1392)\n\nL'analisi della rappresentazione familiare complessiva tra tutti i ruoli (priore, anziano, notaio, cancelliere) ha rivelato la predominanza di alcune famiglie nel periodo tra il 1369 e il 1392. La seguente tabella mostra le 10 famiglie più rappresentate, basata sulla frequenza di apparizione nel dataset:\n\n| Famiglia         | Frequenza |\n| :--------------- | :-------- |\n"""
for family, count in top_10_families.items():
    gen_family_section += f"| {family:<16} | {count:<9} |\n"
gen_family_section += "\nSi osserva che la famiglia 'Da San Casciano' è stata la più presente, seguita da 'Alliata' e 'de Cascina'.\n"

# 2. Rappresentazione Familiare per il Decennio 1370-1379
decade_family_section = """### 2. Rappresentazione Familiare per il Decennio 1370-1379\n\nFocalizzando l'attenzione sul decennio specifico 1370-1379, la composizione delle famiglie più rappresentate tra gli 'Anziani' mostra alcune differenze. Le 5 famiglie più rappresentate in questo periodo sono:\n\n| Famiglia         | Frequenza |\n| :--------------- | :-------- |\n"""
for family, count in top_5_families_1370s.items():
    decade_family_section += f"| {family:<16} | {count:<9} |\n"
decade_family_section += "\nIn questo decennio, 'Da San Casciano' mantiene una forte presenza, con 'Bonconti' e 'de Vico' che emergono come attori significativi.\n"

# 3. Prevalenza Professionale tra gli Anziani
profession_section = """### 3. Prevalenza Professionale tra gli Anziani\n\nL'analisi delle professioni tra gli 'Anziani' ha identificato diverse categorie professionali prevalenti. Le 10 professioni più comuni sono:\n\n| Professione                      | Frequenza |\n| :------------------------------- | :-------- |\n"""
for profession, count in top_10_professions.items():
    profession_section += f"| {profession:<30} | {count:<9} |\n"
profession_section += "\nIl 'Notarius' è di gran lunga la professione più rappresentata, suggerendo l'importanza dei notai nella gestione pubblica dell'epoca, seguito da 'Vinarius' e 'Tabernarius'.\n"

# 4. Distribuzione delle Cariche per le Famiglie Principali
role_dist_section = """### 4. Distribuzione delle Cariche per le Famiglie Principali\n\nLa distribuzione delle cariche ('ruolo') tra le famiglie più rappresentate (come identificate nell'analisi generale) fornisce un quadro più dettagliato della loro influenza. La tabella seguente illustra come le cariche di 'anziano #1', 'anziano #2', 'canc. maior', 'notaio anziani' e 'priore' si distribuiscono tra queste famiglie. Il grafico a barre generato in precedenza visualizza questa distribuzione in modo più intuitivo.\n\n"""
role_dist_section += role_distribution.to_markdown(numalign="left", stralign="left")
role_dist_section += """\n\n**Osservazioni chiave dalla distribuzione delle cariche:**\n\n*   **Famiglie Dominanti in un Ruolo:** Famiglie come 'Alliata' e 'Bonconti' mostrano una forte inclinazione verso il ruolo di 'priore', mentre 'Astarii' ha una presenza equilibrata tra 'anziano #1' e 'priore'.\n*   **Diversificazione dei Ruoli:** 'Da San Casciano' è ben rappresentata in più ruoli, inclusi 'notaio anziani' e 'priore', indicando una partecipazione più diversificata nella vita pubblica. Anche 'de Campo' e 'de Cascina' mostrano una distribuzione dei ruoli più ampia, includendo 'canc. maior' e 'notaio anziani'.\n*   **Concentrazione su Anziano:** Famiglie come 'de Cascina' e 'Astarii' hanno un numero significativo di 'anziano #1'.\n"""

kb_conclusion = """\nQueste analisi forniscono una base per comprendere le dinamiche socio-politiche di Pisa in questo periodo storico, evidenziando il potere e l'influenza di specifiche famiglie e categorie professionali nella gestione della città.\n"""

knowledge_base_content = kb_intro + gen_family_section + decade_family_section + profession_section + role_dist_section + kb_conclusion

print("Knowledge base content successfully generated and stored in 'knowledge_base_content' variable.")

"""**Reasoning**:
The previous code failed because of a `NameError` where `dec_family_section` was used instead of `decade_family_section` within the loop for constructing the decade-specific family representation. I need to correct this variable name to `decade_family_section` to ensure the markdown content is built correctly.


"""

kb_intro = """## Knowledge Base: Analisi delle Cariche Politiche a Pisa (1369-1392)\n\nQuesto documento riassume le principali osservazioni e dati estratti dall'analisi delle cariche politiche a Pisa tra il 1369 e il 1392, con un focus sulla rappresentazione familiare, professionale e la distribuzione dei ruoli.\n"""

# 1. Rappresentazione Familiare Generale (1369-1392)
gen_family_section = """### 1. Rappresentazione Familiare Generale (1369-1392)\n\nL'analisi della rappresentazione familiare complessiva tra tutti i ruoli (priore, anziano, notaio, cancelliere) ha rivelato la predominanza di alcune famiglie nel periodo tra il 1369 e il 1392. La seguente tabella mostra le 10 famiglie più rappresentate, basata sulla frequenza di apparizione nel dataset:\n\n| Famiglia         | Frequenza |\n| :--------------- | :-------- |\n"""
for family, count in top_10_families.items():
    gen_family_section += f"| {family:<16} | {count:<9} |\n"
gen_family_section += "\nSi osserva che la famiglia 'Da San Casciano' è stata la più presente, seguita da 'Alliata' e 'de Cascina'.\n"

# 2. Rappresentazione Familiare per il Decennio 1370-1379
decade_family_section = """### 2. Rappresentazione Familiare per il Decennio 1370-1379\n\nFocalizzando l'attenzione sul decennio specifico 1370-1379, la composizione delle famiglie più rappresentate tra gli 'Anziani' mostra alcune differenze. Le 5 famiglie più rappresentate in questo periodo sono:\n\n| Famiglia         | Frequenza |\n| :--------------- | :-------- |\n"""
for family, count in top_5_families_1370s.items():
    decade_family_section += f"| {family:<16} | {count:<9} |\n"
decade_family_section += "\nIn questo decennio, 'Da San Casciano' mantiene una forte presenza, con 'Bonconti' e 'de Vico' che emergono come attori significativi.\n"

# 3. Prevalenza Professionale tra gli Anziani
profession_section = """### 3. Prevalenza Professionale tra gli Anziani\n\nL'analisi delle professioni tra gli 'Anziani' ha identificato diverse categorie professionali prevalenti. Le 10 professioni più comuni sono:\n\n| Professione                      | Frequenza |\n| :------------------------------- | :-------- |\n"""
for profession, count in top_10_professions.items():
    profession_section += f"| {profession:<30} | {count:<9} |\n"
profession_section += "\nIl 'Notarius' è di gran lunga la professione più rappresentata, suggerendo l'importanza dei notai nella gestione pubblica dell'epoca, seguito da 'Vinarius' e 'Tabernarius'.\n"

# 4. Distribuzione delle Cariche per le Famiglie Principali
role_dist_section = """### 4. Distribuzione delle Cariche per le Famiglie Principali\n\nLa distribuzione delle cariche ('ruolo') tra le famiglie più rappresentate (come identificate nell'analisi generale) fornisce un quadro più dettagliato della loro influenza. La tabella seguente illustra come le cariche di 'anziano #1', 'anziano #2', 'canc. maior', 'notaio anziani' e 'priore' si distribuiscono tra queste famiglie. Il grafico a barre generato in precedenza visualizza questa distribuzione in modo più intuitivo.\n\n"""
role_dist_section += role_distribution.to_markdown(numalign="left", stralign="left")
role_dist_section += """\n\n**Osservazioni chiave dalla distribuzione delle cariche:**\n\n*   **Famiglie Dominanti in un Ruolo:** Famiglie come 'Alliata' e 'Bonconti' mostrano una forte inclinazione verso il ruolo di 'priore', mentre 'Astarii' ha una presenza equilibrata tra 'anziano #1' e 'priore'.\n*   **Diversificazione dei Ruoli:** 'Da San Casciano' è ben rappresentata in più ruoli, inclusi 'notaio anziani' e 'priore', indicando una partecipazione più diversificata nella vita pubblica. Anche 'de Campo' e 'de Cascina' mostrano una distribuzione dei ruoli più ampia, includendo 'canc. maior' e 'notaio anziani'.\n*   **Concentrazione su Anziano:** Famiglie come 'de Cascina' e 'Astarii' hanno un numero significativo di 'anziano #1'.\n"""

kb_conclusion = """\nQueste analisi forniscono una base per comprendere le dinamiche socio-politiche di Pisa in questo periodo storico, evidenziando il potere e l'influenza di specifiche famiglie e categorie professionali nella gestione della città.\n"""

knowledge_base_content = kb_intro + gen_family_section + decade_family_section + profession_section + role_dist_section + kb_conclusion

print("Knowledge base content successfully generated and stored in 'knowledge_base_content' variable.")

"""**Reasoning**:
The `knowledge_base_content` variable now holds the complete markdown string. The next logical step is to write this string to a file named `knowledge_base.md`, as specified in the task.


"""

with open('knowledge_base.md', 'w') as f:
    f.write(knowledge_base_content)
print("Knowledge base successfully exported to 'knowledge_base.md'.")

"""## Final Task

### Subtask:
Fornisci un riepilogo dell'analisi completa, pronta per essere utilizzata come knowledge base.

## Summary:

### Data Analysis Key Findings

*   **Overall Family Representation (1369-1392):** The 'Da San Casciano' family was the most prominent across all roles (priore, anziano, notaio, cancelliere), followed by 'Alliata' and 'de Cascina'.
*   **Decade-Specific Family Representation (1370-1379, among 'Anziani'):** In this specific decade, 'Da San Casciano' maintained a strong presence, with 'Bonconti' and 'de Vico' emerging as significant families.
*   **Professional Prevalence (among 'Anziani'):** The 'Notarius' (notary) was by far the most represented profession, highlighting the importance of notaries in public administration during this period. It was followed by 'Vinarius' (wine merchant) and 'Tabernarius' (tavern keeper).
*   **Role Distribution among Principal Families:**
    *   Families such as 'Alliata' and 'Bonconti' demonstrated a strong inclination towards the 'priore' (prior) role.
    *   The 'Astarii' family exhibited an balanced presence in both the 'anziano #1' and 'priore' roles.
    *   'Da San Casciano', 'de Campo', and 'de Cascina' showed a diversified participation across various public roles, including 'notaio anziani' and 'canc. maior', indicating broader involvement in public life.
    *   'de Cascina' and 'Astarii' also held a significant number of 'anziano #1' positions.

### Insights or Next Steps

*   The generated `knowledge_base.md` provides a structured and comprehensive summary of key socio-political dynamics in Pisa from 1369-1392, suitable for integration into a chatbot or knowledge management system.
*   Further analysis could explore the underlying reasons for the dominance of specific families and professions, such as economic power, social connections, or institutional structures, to provide a deeper understanding of Pisa's historical governance.
"""