# -*- coding: utf-8 -*-
"""Dataviz Gennaro Savi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qnVGIiCuLUqiRp4MrVYDAJ3dwGxemDC0

# Pre Processing o preparazione df
"""

import pandas as pd

file_path = '/content/Lista di Savi e Cerchi di potere.xlsx'

df = pd.read_excel(file_path, sheet_name = 0)
print(f"Successfully loaded {len(df)} rows and {len(df.columns)} columns.")

# Eliminiamo doppi spazi bianchi nei nomi delle colonne
df.columns = df.columns.str.strip()
# Tutto in minuscolo
df.columns = df.columns.str.lower()

df.head()

import pandas as pd

# L'errore era dovuto a una discrepanza tra le colonne selezionate e i nuovi nomi.
# Usiamo gli indici di colonna per evitare problemi con nomi duplicati (es. 'attestazione savi')

column_groups = [
    (0, 1, 2, 'ponte'),      # ponte
    (3, 4, 5, 'foriporta'),  # foriporta
    (6, 7, 8, 'medio'),      # medio
    (9, 10, 11, 'kinzica')   # kinzica
]

pivoted_dfs_list = []

for col_n, col_n1, col_n2, q_name in column_groups:
    # Selezioniamo le colonne per posizione
    temp_df = df.iloc[:, [col_n, col_n1, col_n2]].copy()

    # Rinominiamo esplicitamente
    temp_df.columns = ['nome', 'attestazioni_savi', 'attestazioni_anzianato']

    # Aggiungiamo il quartiere
    temp_df['quartiere'] = q_name

    pivoted_dfs_list.append(temp_df)

# Uniamo tutto
pivot_df = pd.concat(pivoted_dfs_list, ignore_index=True)

# Pulizia righe vuote
pivot_df = pivot_df.dropna(subset=['nome']).reset_index(drop=True)

print("Pivot DF creato con successo:")
print(pivot_df.head())
print(f"\nTotale righe: {len(pivot_df)}")

pivot_df

import pandas as pd
import re

# 1. Estrazione numero attestazioni Savi (1372 e 1377)
def extract_attestations(text, year):
    if pd.isna(text):
        return 0
    # Pattern flessibile: cerca X seguito opzionalmente da spazi, un numero, e poi l'anno
    pattern = rf"X\s*(\d+)\s*=\s*.*?{year}"
    match = re.search(pattern, str(text), re.IGNORECASE)
    return int(match.group(1)) if match else 0

pivot_df['attestazioni_1372'] = pivot_df['attestazioni_savi'].apply(lambda x: extract_attestations(x, 1372))
pivot_df['attestazioni_1377'] = pivot_df['attestazioni_savi'].apply(lambda x: extract_attestations(x, 1377))

# 2. Gestione colonna Nobile
pivot_df['Nobile'] = pivot_df['attestazioni_anzianato'].astype(str).str.strip().str.lower().apply(lambda x: 'Sì' if x == 'nobile' else 'No')

# 3. Esplosione delle attestazioni anzianato
# Filtriamo chi non è nobile per processare le stringhe di partecipazione
def split_anzianato(row):
    text = str(row['attestazioni_anzianato'])
    if row['Nobile'] == 'Sì' or text.lower() == 'nan':
        return [{'anno': None, 'mesi': None}]

    # Separiamo per '//'
    parts = [p.strip() for p in text.split('//') if p.strip()]
    results = []
    for part in parts:
        # Regex per estrarre anno (4 cifre) e mesi (testo prima dell'anno)
        year_match = re.search(r'(\d{4})', part)
        year = year_match.group(1) if year_match else None
        # I mesi sono solitamente all'inizio prima dell'anno
        mesi = part.split(year)[0].strip() if year else part
        results.append({'anno': year, 'mesi': mesi})
    return results

# Creiamo una lista di dizionari espansa
expanded_data = []
for _, row in pivot_df.iterrows():
    attestazioni = split_anzianato(row)
    for att in attestazioni:
        new_row = row.to_dict()
        new_row.update(att)
        expanded_data.append(new_row)

final_df = pd.DataFrame(expanded_data)

# Pulizia finale
final_df = final_df.drop(columns=['attestazioni_anzianato'])

print("DataFrame elaborato ed esploso:")
print(final_df.head(10))
print(f"\nNuovo totale righe dopo esplosione: {len(final_df)}")

df = final_df.iloc[:-1,:]



mesi_anno_pisano = {
    'Aprile': 1,
    'Maggio': 2,
    'Giugno': 3,
    'Luglio': 4,
    'Agosto': 5,
    'Settembre': 6,
    'Ottobre': 7,
    'Novembre': 8,
    'Dicembre': 9,
    'Gennaio': 10,
    'Febbraio': 11,
    'Marzo': 12
}

import pandas as pd
from datetime import date

# Assicuriamoci che df sia una copia indipendente
df = df.copy()

# 1. Normalizzazione colonna mesi
df.loc[:, 'mesi'] = df['mesi'].astype(str).str.replace('_', '-', regex=False)

date_inizio_mandato = []
date_fine_mandato = []

for i in range(len(df)):
    anni = df.iloc[i]['anno']
    mesi = df.iloc[i]['mesi']

    # Inizializzazione
    data_inizio = None
    data_fine = None

    if isinstance(mesi, str) and mesi.lower() not in ['none', 'nan']:
        parti_mesi = [m.strip().capitalize() for m in mesi.split('-') if m.strip()]

        if len(parti_mesi) >= 2:
            mese_inizio_str = parti_mesi[0]
            mese_fine_str = parti_mesi[-1]

            m_in = mesi_anno_pisano.get(mese_inizio_str)
            m_fi = mesi_anno_pisano.get(mese_fine_str)

            if m_in and m_fi and anni:
                # Gestione anni (singolo o range 1386-1387)
                if isinstance(anni, str) and '-' in anni:
                    y_parts = anni.split('-')
                    y_in, y_fi = int(y_parts[0]), int(y_parts[1])
                else:
                    y_in = y_fi = int(anni)

                try:
                    data_inizio = date(y_in, m_in, 1)
                    data_fine = date(y_fi, m_fi, 1)
                except ValueError:
                    pass

    date_inizio_mandato.append(data_inizio)
    date_fine_mandato.append(data_fine)

# Assegnazione
df.loc[:, 'data inizio mandato'] = date_inizio_mandato
df.loc[:, 'data fine mandato'] = date_fine_mandato

print("Date ricalcolate correttamente.")
print(df[['nome', 'mesi', 'anno', 'data inizio mandato', 'data fine mandato']].head())

df

"""### 1. Caricamento e Preparazione dei Dataset
In questa fase carichiamo il dataset dei Savi (precedentemente pulito) e il dataset standardizzato degli Anziani. Creiamo inoltre una versione deduplicata del dataset Anziani per assicurarci di contare **individui fisici** e non mandati ripetuti.
"""

import pandas as pd

# Caricamento Anziani Standardizzati
df_consiglio_anziani = pd.read_csv('/content/dati_standardizzati.csv')

# Assicuriamoci che la colonna famiglia sia minuscola per coerenza
if 'Famiglia' in df_consiglio_anziani.columns:
    df_consiglio_anziani['famiglia'] = df_consiglio_anziani['Famiglia']

# Creazione dataset individui unici (Deduplicazione)
df_anziani_unici = df_consiglio_anziani.drop_duplicates(subset=['nome']).copy()

# Preparazione Savi
df_consiglio_savi = df.copy()

# Guess iniziale della famiglia per i Savi
def get_family_guess(name):
    if pd.isna(name): return "Ignoto"
    parts = str(name).strip().split()
    return parts[-1] if len(parts) > 1 else parts[0]

df_consiglio_savi['famiglia'] = df_consiglio_savi['nome'].apply(get_family_guess)

print(f"Anziani: {len(df_anziani_unici)} individui unici.")
print(f"Savi: {df_consiglio_savi['nome'].nunique()} individui unici.")

"""### 2. Matching dei Nomi (Esatto e Fuzzy)
Per unire i due dataset, utilizziamo una logica a due livelli:
1. **Match Esatto**: Identificazione immediata dei nomi identici.
2. **Match Fuzzy (Levenshtein)**: Calcolo della somiglianza tra i nomi rimanenti, applicando una penale sulla lunghezza dei token e filtrando le particelle amministrative (*ser, di, da, etc.*). Utilizziamo una soglia di **0.857** per confermare l'identità.
"""

# Re-esecuzione del matching fuzzy con gestione corretta delle colonne
mapping_fuzzy = {}
correzione_famiglia_savi = {}

nomi_savi = set(df_consiglio_savi['nome'].unique())
nomi_anziani = set(df_anziani_unici['nome'].unique())

for ns in nomi_savi:
    miglior_score = 0
    miglior_match = None
    for na in nomi_anziani:
        if ns == na:
            miglior_score = 1.0
            miglior_match = na
            break
        # Utilizziamo la funzione di confronto definita in precedenza nel kernel
        score = confronta_nomi_token(ns, na)
        if score > miglior_score:
            miglior_score = score
            miglior_match = na

    if miglior_score > 0.857:
        mapping_fuzzy[ns] = miglior_match
        # Accesso sicuro alla colonna 'famiglia' appena normalizzata
        fam_ufficiale = df_anziani_unici[df_anziani_unici['nome'] == miglior_match]['famiglia'].values[0]
        correzione_famiglia_savi[ns] = fam_ufficiale

# Sincronizziamo le famiglie dei Savi
for nome_savi, fam_vera in correzione_famiglia_savi.items():
    df_consiglio_savi.loc[df_consiglio_savi['nome'] == nome_savi, 'famiglia'] = fam_vera

print(f"Match totali trovati: {len(mapping_fuzzy)}")

"""### 3. Analisi dei Cerchi di Potere
Classifichiamo gli individui in base alla loro partecipazione e ai legami familiari:
- **Cerchio 0**: Nobili presenti solo nei Savi.
- **Cerchio 1/2**: Individui presenti in entrambi i consigli (Elite core).
- **Cerchio 3**: Anziani non presenti nei Savi, ma appartenenti a famiglie che vi hanno partecipato.
- **Cerchio 4**: Anziani senza legami diretti o familiari con i Savi.
"""

# Ricalcolo finale dei cerchi basato su individui unici e famiglie sincronizzate
nomi_savi_in_entrambi = set(mapping_fuzzy.keys())
nobili_savi = df_consiglio_savi[df_consiglio_savi['Nobile'] == 'Sì']['nome'].unique()

cerchio_0_final = [n for n in nobili_savi if n not in nomi_savi_in_entrambi]
cerchio_2_final = list(nomi_savi_in_entrambi)

famiglie_c2 = set(df_consiglio_savi[df_consiglio_savi['nome'].isin(cerchio_2_final)]['famiglia'].unique())

nomi_anziani_matchati = set(mapping_fuzzy.values())
anziani_esterni_unici = df_anziani_unici[~df_anziani_unici['nome'].isin(nomi_anziani_matchati)]

cerchio_3_final = anziani_esterni_unici[anziani_esterni_unici['famiglia'].isin(famiglie_c2)]['nome'].unique().tolist()
cerchio_4_final = anziani_esterni_unici[~anziani_esterni_unici['famiglia'].isin(famiglie_c2)]['nome'].unique().tolist()

print(f"Risultati Finali (Individui Fisici):")
print(f"- Cerchio 0 (Nobili isolati): {len(cerchio_0_final)}")
print(f"- Cerchio 2 (Ponte diretto): {len(cerchio_2_final)}")
print(f"- Cerchio 3 (Rete familiare): {len(cerchio_3_final)}")
print(f"- Cerchio 4 (Esterni): {len(cerchio_4_final)}")

"""### 4. Visualizzazione Finale dei Cerchi di Potere
Grafico riassuntivo della distribuzione degli individui fisici unici all'interno del sistema politico pisano.
"""

import matplotlib.pyplot as plt

labels = ['Cerchio 0', 'Cerchio 2', 'Cerchio 3', 'Cerchio 4']
values = [len(cerchio_0_final), len(cerchio_2_final), len(cerchio_3_final), len(cerchio_4_final)]
colors = ['#3498db', '#2ecc71', '#e74c3c', '#9b59b6']

plt.figure(figsize=(10, 6))
plt.bar(labels, values, color=colors)
plt.title('Distribuzione Finale degli Individui per Cerchi di Potere (Deduplicati)')
plt.ylabel('Numero di Persone Fisiche')

for i, v in enumerate(values):
    plt.text(i, v + 20, str(v), ha='center', fontweight='bold')

plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""### 4. Visualizzazione Finale dei Cerchi di Potere
Grafico riassuntivo della distribuzione degli individui fisici unici all'interno del sistema politico pisano.
"""

import matplotlib.pyplot as plt

labels = ['Cerchio 0', 'Cerchio 2', 'Cerchio 3', 'Cerchio 4']
values = [len(cerchio_0_final), len(cerchio_2_final), len(cerchio_3_final), len(cerchio_4_final)]
colors = ['#3498db', '#2ecc71', '#e74c3c', '#9b59b6']

plt.figure(figsize=(10, 6))
plt.bar(labels, values, color=colors)
plt.title('Distribuzione Finale degli Individui per Cerchi di Potere (Deduplicati)')
plt.ylabel('Numero di Persone Fisiche')

for i, v in enumerate(values):
    plt.text(i, v + 20, str(v), ha='center', fontweight='bold')

plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""### 4. Visualizzazione Finale dei Cerchi di Potere
Grafico riassuntivo della distribuzione degli individui fisici unici all'interno del sistema politico pisano.
"""

import matplotlib.pyplot as plt

labels = ['Cerchio 0', 'Cerchio 2', 'Cerchio 3', 'Cerchio 4']
values = [len(cerchio_0_final), len(cerchio_2_final), len(cerchio_3_final), len(cerchio_4_final)]
colors = ['#3498db', '#2ecc71', '#e74c3c', '#9b59b6']

plt.figure(figsize=(10, 6))
plt.bar(labels, values, color=colors)
plt.title('Distribuzione Finale degli Individui per Cerchi di Potere (Deduplicati)')
plt.ylabel('Numero di Persone Fisiche')

for i, v in enumerate(values):
    plt.text(i, v + 20, str(v), ha='center', fontweight='bold')

plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# 1. Caricamento dati
df_consiglio_anziani = pd.read_csv('/content/dati_standardizzati.csv')
df_consiglio_savi = df.copy()

# Funzione helper solo per i Savi (punto di partenza)
def get_family_guess(name):
    if pd.isna(name): return "Ignoto"
    parts = str(name).strip().split()
    return parts[-1] if len(parts) > 1 else parts[0]

df_consiglio_savi['famiglia'] = df_consiglio_savi['nome'].apply(get_family_guess)

# NOTA: df_consiglio_anziani ha già la colonna 'Famiglia' dai dati standardizzati
# Ci assicuriamo solo che il nome della colonna sia coerente (minuscolo)
if 'Famiglia' in df_consiglio_anziani.columns:
    df_consiglio_anziani['famiglia'] = df_consiglio_anziani['Famiglia']

nomi_savi = set(df_consiglio_savi['nome'].unique())
nomi_anziani_df = df_consiglio_anziani[['nome', 'famiglia']].drop_duplicates('nome')
nomi_anziani = set(nomi_anziani_df['nome'].unique())

# 2. Fuzzy Matching con aggiornamento Famiglia
mapping_fuzzy = {}
# Dizionario per correggere la famiglia del Savio in base al match trovato negli Anziani
correzione_famiglia_savi = {}

for ns in nomi_savi:
    miglior_score = 0
    miglior_match = None

    for na in nomi_anziani:
        if ns == na:
            miglior_score = 1.0
            miglior_match = na
            break
        score = confronta_nomi_token(ns, na)
        if score > miglior_score:
            miglior_score = score
            miglior_match = na

    if miglior_score > 0.857:
        mapping_fuzzy[ns] = miglior_match
        # Recuperiamo la famiglia ufficiale dal df standardizzato
        famiglia_ufficiale = nomi_anziani_df[nomi_anziani_df['nome'] == miglior_match]['famiglia'].values[0]
        correzione_famiglia_savi[ns] = famiglia_ufficiale

# Applichiamo la famiglia del dataset standardizzato ai matchati nei Savi
for nome_savi, fam_vera in correzione_famiglia_savi.items():
    df_consiglio_savi.loc[df_consiglio_savi['nome'] == nome_savi, 'famiglia'] = fam_vera

# 3. Ricalcolo Cerchi
nomi_savi_in_entrambi = set(mapping_fuzzy.keys())
nobili_savi = df_consiglio_savi[df_consiglio_savi['Nobile'] == 'Sì']['nome'].unique()

cerchio_0_fuzzy = [n for n in nobili_savi if n not in nomi_savi_in_entrambi]
cerchio_1_fuzzy = [n for n in nobili_savi if n in nomi_savi_in_entrambi]
cerchio_2_fuzzy = list(nomi_savi_in_entrambi)

# Famiglie del cerchio 2 (ora usando i dati corretti dal CSV)
famiglie_cerchio_2_fuzzy = set(df_consiglio_savi[df_consiglio_savi['nome'].isin(cerchio_2_fuzzy)]['famiglia'].unique())

nomi_anziani_matchati = set(mapping_fuzzy.values())
anziani_non_savi_fuzzy = df_consiglio_anziani[~df_consiglio_anziani['nome'].isin(nomi_anziani_matchati)]

cerchio_3_fuzzy = anziani_non_savi_fuzzy[anziani_non_savi_fuzzy['famiglia'].isin(famiglie_cerchio_2_fuzzy)]['nome'].unique().tolist()
cerchio_4_fuzzy = anziani_non_savi_fuzzy[~anziani_non_savi_fuzzy['famiglia'].isin(famiglie_cerchio_2_fuzzy)]['nome'].unique().tolist()

print("Analisi aggiornata: la famiglia dei match fuzzy ora segue il dataset standardizzato.")

import pandas as pd
from IPython.display import display

def show_circle_minimal(names, source_df, title):
    print(f"\n--- {title} ---")
    details = source_df[source_df['nome'].isin(names)][['nome', 'famiglia']].drop_duplicates()
    if details.empty:
        print("Nessun individuo trovato.")
    else:
        # Mostriamo un numero ridotto di righe per evitare troncamenti nel log
        display(details.head(10))
        print(f"Totale nel gruppo: {len(details)}")

# Mostriamo i cerchi che mancavano o erano troncati
show_circle_minimal(cerchio_3, df_consiglio_anziani, 'Cerchio 3: Anziani con famiglia nei Savi')
show_circle_minimal(cerchio_4, df_consiglio_anziani, 'Cerchio 4: Anziani senza legami nei Savi')

# Mostriamo anche un riepilogo generale per completezza
print("\n--- RIEPILOGO GENERALE ---")
print(f"Cerchio 0: {len(cerchio_0)} Nobili solo Savi")
print(f"Cerchio 1: {len(cerchio_1)} Nobili in entrambi")
print(f"Cerchio 2: {len(cerchio_2)} Individui in entrambi")
print(f"Cerchio 3: {len(cerchio_3)} Anziani con famiglia nei Savi")
print(f"Cerchio 4: {len(cerchio_4)} Anziani senza legami")



# Calcolo degli individui nei Savi che non hanno un match negli Anziani
individui_savi_senza_match = [nome for nome in nomi_savi if nome not in nomi_anziani]

print(f"Numero di individui unici nei Savi: {len(nomi_savi)}")
print(f"Numero di individui nei Savi senza match negli Anziani: {len(individui_savi_senza_match)}")

# Mostriamo i primi 10 nomi per riferimento
if individui_savi_senza_match:
    print("\nPrimi 10 individui senza match:")
    for nome in individui_savi_senza_match[:10]:
        print(f"- {nome}")



def levenshtein_distance(s1, s2):
    if len(s1) < len(s2): return levenshtein_distance(s2, s1)
    if len(s2) == 0: return len(s1)
    previous_row = range(len(s2) + 1)
    for i, c1 in enumerate(s1):
        current_row = [i + 1]
        for j, c2 in enumerate(s2):
            insertions = previous_row[j + 1] + 1
            deletions = current_row[j] + 1
            substitutions = previous_row[j] + (c1 != c2)
            current_row.append(min(insertions, deletions, substitutions))
        previous_row = current_row
    return previous_row[-1]

def somiglianza_parole(w1, w2):
    if w1 == w2: return 1.0
    max_len = max(len(w1), len(w2))
    if max_len == 0: return 0.0
    return 1.0 - (levenshtein_distance(w1, w2) / max_len)

def confronta_nomi_token(nome1, nome2):
    # Lista di particelle e titoli da escludere
    stop_words = {'di', 'ser', 'de', 'da', 'q.', 'fu', 'd.', 'del', 'degli', 'della'}

    def clean_tokens(name):
        tokens = str(name).lower().replace(',', '').split()
        return [t for t in tokens if t not in stop_words]

    parole1 = clean_tokens(nome1)
    parole2 = clean_tokens(nome2)

    len1, len2 = len(parole1), len(parole2)
    if len1 == 0 or len2 == 0: return 0.0

    # Identifichiamo il set più corto e quello più lungo
    p_corte = parole1 if len1 <= len2 else parole2
    p_lunghe = list(parole2 if len1 <= len2 else parole1)

    somma_somiglianze = 0.0
    for p_c in p_corte:
        miglior_punteggio = 0.0
        miglior_idx = -1
        for i, p_l in enumerate(p_lunghe):
            punteggio = somiglianza_parole(p_c, p_l)
            if punteggio > miglior_punteggio:
                miglior_punteggio = punteggio
                miglior_idx = i

        if miglior_idx != -1:
            somma_somiglianze += miglior_punteggio
            p_lunghe.pop(miglior_idx)

    # Punteggio base
    punteggio_base = somma_somiglianze / len(p_corte)

    # Penalizzazione per differenza di lunghezza dei set di token puliti
    fattore_penalita = min(len1, len2) / max(len1, len2)

    return punteggio_base * fattore_penalita

# Ricalcolo con la nuova logica (Senza particelle)
risultati_aggiornati = []
nomi_savi_da_testare = [n for n in nomi_savi if n not in nomi_anziani]

for ns in nomi_savi_da_testare:
    for na in nomi_anziani:
        score = confronta_nomi_token(ns, na)
        if score > 0.6:
            risultati_aggiornati.append({'Savi': ns, 'Anziani': na, 'Somiglianza': round(score, 3)})

df_somiglianza_penalizzato = pd.DataFrame(risultati_aggiornati).sort_values(by='Somiglianza', ascending=False)

print("Top 20 potenziali match (Escludendo 'ser', 'di', etc.):")
display(df_somiglianza_penalizzato.head(20))

df_somiglianza_penalizzato

import matplotlib.pyplot as plt
import pandas as pd

# 1. Identificazione dei match fuzzy con soglia > 0.857
# Creiamo un dizionario di mappatura: Nome Savi -> Nome Anziani (se match trovato)
mapping_fuzzy = {}

for ns in nomi_savi:
    miglior_score = 0
    miglior_match = None

    for na in nomi_anziani:
        # Se è un match esatto, non serve il calcolo fuzzy
        if ns == na:
            miglior_score = 1.0
            miglior_match = na
            break

        score = confronta_nomi_token(ns, na)
        if score > miglior_score:
            miglior_score = score
            miglior_match = na

    if miglior_score > 0.857:
        mapping_fuzzy[ns] = miglior_match

# 2. Aggiornamento dei set basato sulla logica fuzzy
# Consideriamo 'in entrambi' se c'è un match fuzzy
nomi_savi_in_entrambi = set(mapping_fuzzy.keys())

# 3. Ricalcolo dei Cerchi di Potere

# Cerchio 0: Nobili solo nei Savi (senza match fuzzy negli Anziani)
cerchio_0_fuzzy = [n for n in nobili_savi if n not in nomi_savi_in_entrambi]

# Cerchio 1: Nobili in entrambi (con match fuzzy)
cerchio_1_fuzzy = [n for n in nobili_savi if n in nomi_savi_in_entrambi]

# Cerchio 2: Qualsiasi individuo in entrambi i consigli (Incrocio Fuzzy)
cerchio_2_fuzzy = list(nomi_savi_in_entrambi)

# Estrazione famiglie dal Cerchio 2 (usando i nomi originali dei Savi)
famiglie_cerchio_2_fuzzy = set(df_consiglio_savi[df_consiglio_savi['nome'].isin(cerchio_2_fuzzy)]['famiglia'].unique())

# Cerchio 3: In Anziani, non matchati con Savi, ma famiglia nel Cerchio 2
# Usiamo i nomi degli Anziani che non sono stati 'bersaglio' di un match fuzzy
nomi_anziani_matchati = set(mapping_fuzzy.values())
anziani_non_savi_fuzzy = df_consiglio_anziani[~df_consiglio_anziani['nome'].isin(nomi_anziani_matchati)]

cerchio_3_fuzzy = anziani_non_savi_fuzzy[anziani_non_savi_fuzzy['famiglia'].isin(famiglie_cerchio_2_fuzzy)]['nome'].unique().tolist()

# Cerchio 4: In Anziani, non matchati, famiglia NON nel Cerchio 2
cerchio_4_fuzzy = anziani_non_savi_fuzzy[~anziani_non_savi_fuzzy['famiglia'].isin(famiglie_cerchio_2_fuzzy)]['nome'].unique().tolist()

# 4. Visualizzazione
gruppi = ['Cerchio 0', 'Cerchio 1', 'Cerchio 2', 'Cerchio 3', 'Cerchio 4']
counts = [len(cerchio_0_fuzzy), len(cerchio_1_fuzzy), len(cerchio_2_fuzzy), len(cerchio_3_fuzzy), len(cerchio_4_fuzzy)]

plt.figure(figsize=(10, 6))
plt.bar(gruppi, counts, color=['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd'])
plt.title('Distribuzione Cerchi di Potere (Logica Fuzzy > 0.857)')
plt.ylabel('Numero di Individui unici')
for i, v in enumerate(counts):
    plt.text(i, v + 0.5, str(v), ha='center')
plt.show()

print(f"--- Risultati con Soglia Fuzzy 0.857 ---")
print(f"Cerchio 0 (Nobili solo Savi): {len(cerchio_0_fuzzy)}")
print(f"Cerchio 1 (Nobili entrambi - Match Fuzzy): {len(cerchio_1_fuzzy)}")
print(f"Cerchio 2 (Incrocio totale - Match Fuzzy): {len(cerchio_2_fuzzy)}")
print(f"Cerchio 3 (Anziani esterni, famiglia nel C2): {len(cerchio_3_fuzzy)}")
print(f"Cerchio 4 (Anziani esterni, famiglia nuova): {len(cerchio_4_fuzzy)}")

# Esempio di alcuni match recuperati
print("\nEsempi di match fuzzy identificati (Savi -> Anziani):")
for i, (ks, va) in enumerate(list(mapping_fuzzy.items())):
    if ks != va:
        print(f"- {ks}  ==>  {va}")
    if i > 20: break

def get_family_counts(names, source_df):
    df_subset = source_df[source_df['nome'].isin(names)].copy()
    counts = df_subset.drop_duplicates(subset=['nome'])['famiglia'].value_counts().reset_index()
    counts.columns = ['Famiglia', 'Numero Individui']
    return counts

famiglie_c0 = get_family_counts(cerchio_0_fuzzy, df_consiglio_savi)
famiglie_c1 = get_family_counts(cerchio_1_fuzzy, df_consiglio_savi)
famiglie_c2 = get_family_counts(cerchio_2_fuzzy, df_consiglio_savi)
famiglie_c3 = get_family_counts(cerchio_3_fuzzy, df_consiglio_anziani)
famiglie_c4 = get_family_counts(cerchio_4_fuzzy, df_consiglio_anziani)

print("=== ANALISI DELLE FAMIGLIE PER CERCHIO (CORRETTA) ===")
print("\nTop 15 Cerchio 2 (Match Fuzzy):")
display(famiglie_c2.head(15))
print("\nTop 15 Cerchio 3 (Legami Familiari):")
display(famiglie_c3.head(15))
print("\nTop 15 Cerchio 4 (Nuove Famiglie):")
display(famiglie_c4.head(15))
print("\nTop 15 Cerchio 0 (Nobili esclusivi):")
display(famiglie_c0.head(15))



df_consiglio_anziani

import pandas as pd

# Verifichiamo il numero di righe totali vs individui unici nel dataset Anziani
totale_mandati = len(df_consiglio_anziani)
individui_unici = df_consiglio_anziani['nome'].nunique()

print(f"Dataset Anziani (Standardizzato):")
print(f"- Totale righe (mandati): {totale_mandati}")
print(f"- Individui unici: {individui_unici}")

# Creiamo un dataframe con una riga per ogni individuo unico
# Teniamo la colonna 'famiglia' (che è costante per lo stesso nome)
df_anziani_unici = df_consiglio_anziani.drop_duplicates(subset=['nome']).copy()

print(f"\nCreato 'df_anziani_unici' con {len(df_anziani_unici)} righe.")

"""Ora che abbiamo gli individui unici, ricalcoliamo rapidamente i volumi dei cerchi 3 e 4 per assicurarci che i numeri visualizzati nel grafico precedente fossero corretti (basati sulle persone e non sui mandati)."""

# Ricalcolo Cerchio 3 e 4 basato su individui unici
# mapping_fuzzy contiene già i match unici (Savi -> Anziani)

nomi_anziani_matchati = set(mapping_fuzzy.values())
anziani_esterni_unici = df_anziani_unici[~df_anziani_unici['nome'].isin(nomi_anziani_matchati)]

cerchio_3_unici = anziani_esterni_unici[anziani_esterni_unici['famiglia'].isin(famiglie_cerchio_2_fuzzy)]['nome'].unique().tolist()
cerchio_4_unici = anziani_esterni_unici[~anziani_esterni_unici['famiglia'].isin(famiglie_cerchio_2_fuzzy)]['nome'].unique().tolist()

print(f"Conteggio corretto (Individui Fisici):")
print(f"Cerchio 3 (Parenti): {len(cerchio_3_unici)}")
print(f"Cerchio 4 (Estranei): {len(cerchio_4_unici)}")

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

# 1. Preparazione delle statistiche familiari per i grafici
def get_ranked_families(names, source_df):
    df_sub = source_df[source_df['nome'].isin(names)].copy()
    counts = df_sub.drop_duplicates(subset=['nome'])['famiglia'].value_counts().reset_index()
    counts.columns = ['Famiglia', 'Numero Individui']
    return counts

# Calcoliamo i dati necessari per i grafici
stats_c2 = get_ranked_families(cerchio_2_final, df_consiglio_savi)
stats_c3 = get_ranked_families(cerchio_3_final, df_consiglio_anziani)

# 2. Impostazioni estetiche
sns.set_theme(style="whitegrid")
plt.rcParams['font.family'] = 'sans-serif'

# Preparazione Dati Storytelling
labels = ['Cerchio 0\n(Nobili)', 'Cerchio 2\n(L\'Elite)', 'Cerchio 3\n(La Rete)', 'Cerchio 4\n(Esterni)']
values = [len(cerchio_0_final), len(cerchio_2_final), len(cerchio_3_final), len(cerchio_4_final)]
descriptions = [
    "Aristocrazia pura\n(Solo Savi)",
    "Il nucleo del potere\n(In entrambi i consigli)",
    "L'estensione familiare\n(Parenti dei Savi)",
    "Nuovi attori\n(Senza legami diretti)"
]

# 3. Creazione della figura principale
fig = plt.figure(figsize=(16, 12))
gs = fig.add_gridspec(2, 2, hspace=0.3, wspace=0.3)

# --- QUADRANTE A: La Gerarchia del Potere ---
ax1 = fig.add_subplot(gs[0, 0])
colors = ['#2C3E50', '#27AE60', '#E74C3C', '#8E44AD']
bars = ax1.bar(labels, values, color=colors, alpha=0.8, edgecolor='black', linewidth=1)
ax1.set_title("LA GERARCHIA DEL POTERE PISANO", fontsize=16, fontweight='bold', pad=20)
ax1.set_ylabel("Numero di Individui Fisici")

for bar, desc in zip(bars, descriptions):
    height = bar.get_height()
    ax1.text(bar.get_x() + bar.get_width()/2., height + 20, f'{int(height)}',
             ha='center', va='bottom', fontsize=12, fontweight='bold')
    ax1.text(bar.get_x() + bar.get_width()/2., height / 2, desc,
             ha='center', va='center', color='white', fontsize=9, fontweight='bold',
             bbox=dict(facecolor='black', alpha=0.3, boxstyle='round'))

# --- QUADRANTE B: Egemonia Familiare (Cerchio 3) ---
ax2 = fig.add_subplot(gs[0, 1])
sns.barplot(data=stats_c3.head(10), x='Numero Individui', y='Famiglia', hue='Famiglia', palette='Reds_r', ax=ax2, legend=False)
ax2.set_title("RETE DEL CONSENSO (Top Famiglie C3)", fontsize=14, fontweight='bold')
ax2.set_xlabel("Individui nel consiglio degli Anziani")

# --- QUADRANTE C: Le Famiglie Ponte (Cerchio 2) ---
ax3 = fig.add_subplot(gs[1, 0])
sns.barplot(data=stats_c2.head(10), x='Numero Individui', y='Famiglia', hue='Famiglia', palette='Greens_r', ax=ax3, legend=False)
ax3.set_title("L'ELITE DIRIGENTE (Top Famiglie C2)", fontsize=14, fontweight='bold')
ax3.set_xlabel("Individui con doppia carica")

# --- QUADRANTE D: Infografica Statistica ---
ax4 = fig.add_subplot(gs[1, 1])
ax4.axis('off')
total_p = sum(values)
perc_c3 = (len(cerchio_3_final) / (len(cerchio_3_final) + len(cerchio_4_final))) * 100

text_info = (
    f"REPORT ANALITICO\n"
    f"----------------------------\n"
    f"● Individui mappati: {total_p}\n"
    f"● Tasso di legame familiare: {perc_c3:.1f}%\n"
    f"  (Anziani appartenenti a casate dei Savi)\n\n"
    f"INTERPRETAZIONE:\n"
    f"Il potere pisano del Trecento non è\n"
    f"individuale, ma collettivo. Mentre solo\n"
    f"61 persone occupano il 'cuore' (C2),\n"
    f"queste trascinano con sé una rete di\n"
    f"1.605 parenti. Le famiglie Alliata e\n"
    f"Bonconti emergono come i giganti del\n"
    f"consenso politico."
)

ax4.text(0.05, 0.5, text_info, fontsize=14, va='center', family='serif',
         bbox=dict(facecolor='#FDFEFE', alpha=0.8, boxstyle='round,pad=1', edgecolor='#AED6F1'))

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# 1. Ricalcolo rigoroso dei Cerchi di Potere
# C0: Nobili presenti nel Consiglio dei Savi
cerchio_0 = df_consiglio_savi[df_consiglio_savi['Nobile'] == 'Sì']['nome'].unique().tolist()

# C1: Nobili presenti nel Consiglio degli Anziani (Dovrebbe essere vuoto)
# Verifichiamo se qualche Savio nobile ha un match negli Anziani
cerchio_1 = [ns for ns, na in mapping_fuzzy.items() if ns in cerchio_0]

# C2: Anziani (non nobili) presenti nel Consiglio dei Savi (Elite secondaria)
# Sono i match fuzzy dove il Savio NON è nobile
cerchio_2 = [na for ns, na in mapping_fuzzy.items() if ns not in cerchio_0]

# C3: Anziani la cui famiglia è presente in C2 (Rete Familiare)
famiglie_elite_c2 = set(df_anziani_unici[df_anziani_unici['nome'].isin(cerchio_2)]['famiglia'].unique())
anziani_non_c2 = df_anziani_unici[~df_anziani_unici['nome'].isin(cerchio_2)]

cerchio_3 = anziani_non_c2[anziani_non_c2['famiglia'].isin(famiglie_elite_c2)]['nome'].unique().tolist()

# C4: Anziani senza legami con l'elite dei Savi (Nuovi Attori)
cerchio_4 = anziani_non_c2[~anziani_non_c2['famiglia'].isin(famiglie_elite_c2)]['nome'].unique().tolist()

# 2. Visualizzazione Storytelling Minimalista
plt.rcParams['font.family'] = 'sans-serif'
sns.set_style("white")

labels = ['C0: Nobili',
          'C1: Nobili/Anziani',
          'C2: Elite Savi',
          'C3: Rete Consorterie',
          'C4: Uomini Nuovi']
counts = [len(cerchio_0), len(cerchio_1), len(cerchio_2), len(cerchio_3), len(cerchio_4)]
colors = ['#AAB7B8', '#D5DBDB', '#76D7C4', '#F1948A', '#AED6F1']

fig, ax = plt.subplots(figsize=(14, 8))

# Rimoziome bordi per pulizia visiva
for s in ['top', 'right', 'left']:
    ax.spines[s].set_visible(False)

bars = ax.bar(labels, counts, color=colors, width=0.6, alpha=0.9)

# Etichette dati
for bar in bars:
    yval = bar.get_height()
    ax.text(bar.get_x() + bar.get_width()/2, yval + 30, f'{int(yval)}',
            ha='center', va='bottom', fontsize=13, fontweight='bold', color='#2E4053')

# Titoli e Storytelling
plt.text(-0.5, max(counts) * 1.25, 'Pisa Trecentesca: La Geografia del Potere', fontsize=22, fontweight='bold', color='#1B2631')
plt.text(-0.5, max(counts) * 1.18, 'Dai seggi riservati all\'aristocrazia alla vasta rete di legami familiari delle consorterie emergenti.',
         fontsize=14, color='#5D6D7E', style='italic')

# Nota esplicativa laterale
explanation = (
    "LOGICA DEI CERCHI:\n"
    "● C0: Il patriziato dei Savi\n"
    "● C1: L'impossibile unione (vuoto)\n"
    "● C2: Il ponte politico Anziani-Savi\n"
    "● C3: La forza dei clan familiari\n"
    "● C4: Attori esterni al sistema"
)
plt.text(3.6, max(counts)*0.7, explanation, fontsize=12, color='#283747',
         bbox=dict(facecolor='#F4F6F7', edgecolor='none', boxstyle='round,pad=1'))

ax.set_yticks([])
ax.tick_params(axis='x', colors='#566573', labelsize=12)

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# 1. Preparazione dei dati per le classifiche familiari
def get_family_data(names, source_df):
    subset = source_df[source_df['nome'].isin(names)].copy()
    counts = subset.drop_duplicates(subset=['nome'])['famiglia'].value_counts().reset_index()
    counts.columns = ['Famiglia', 'Conteggio']
    return counts.head(10)

stats_c2 = get_family_data(cerchio_2, df_consiglio_anziani)
stats_c3 = get_family_data(cerchio_3, df_consiglio_anziani)

# 2. Layout del Dashboard
plt.rcParams['font.family'] = 'sans-serif'
fig = plt.figure(figsize=(18, 14))
gs = fig.add_gridspec(2, 2, hspace=0.3, wspace=0.25)

# --- GRAFICO 1: Distribuzione dei Cerchi ---
ax1 = fig.add_subplot(gs[0, :])
labels_c = ['C0: Nobili', 'C1: Nob-Anz', 'C2: Elite Savi', 'C3: Famiglie', 'C4: Nuovi']
counts_c = [len(cerchio_0), len(cerchio_1), len(cerchio_2), len(cerchio_3), len(cerchio_4)]
colors_c = ['#AAB7B8', '#D5DBDB', '#76D7C4', '#F1948A', '#AED6F1']

ax1.bar(labels_c, counts_c, color=colors_c, width=0.6, alpha=0.9)
for i, v in enumerate(counts_c):
    ax1.text(i, v + 15, str(v), ha='center', fontweight='bold', color='#2E4053')

ax1.set_title('GEOGRAFIA DEL POTERE PISANO (XIV Secolo)', fontsize=20, fontweight='bold', pad=15)
ax1.set_yticks([])
sns.despine(ax=ax1, left=True)

# --- GRAFICO 2: Top Famiglie Elite (C2) ---
ax2 = fig.add_subplot(gs[1, 0])
sns.barplot(data=stats_c2, x='Conteggio', y='Famiglia', color='#76D7C4', ax=ax2, alpha=0.8)
ax2.set_title('TOP FAMIGLIE: ELITE SECONDARIA (C2)', fontsize=14, fontweight='bold')
ax2.set_xlabel('Numero di Individui')
ax2.set_ylabel('')
sns.despine(ax=ax2, left=True)

# --- GRAFICO 3: Top Famiglie Rete (C3) ---
ax3 = fig.add_subplot(gs[1, 1])
sns.barplot(data=stats_c3, x='Conteggio', y='Famiglia', color='#F1948A', ax=ax3, alpha=0.8)
ax3.set_title('TOP FAMIGLIE: RETE DEL CONSENSO (C3)', fontsize=14, fontweight='bold')
ax3.set_xlabel('Numero di Individui')
ax3.set_ylabel('')
sns.despine(ax=ax3, left=True)

# Annotazione finale
plt.figtext(0.5, 0.02, "L'analisi evidenzia come poche famiglie (C2) facciano da ponte verso i Savi, trascinando centinaia di parenti (C3) nel sistema politico.",
            ha="center", fontsize=12, style='italic', color='#5D6D7E')

plt.show()

"""### Esportazione Dati Esaustivi
Le seguenti tabelle riassumono la composizione familiare di ogni cerchio. I file CSV verranno salvati nella cartella `/content/` per il download.
"""

import pandas as pd

# Funzione per generare report completi e scaricabili
def generate_and_save_report(names, source_df, circle_name):
    # Estraiamo gli individui unici per quel cerchio
    subset = source_df[source_df['nome'].isin(names)].copy()
    report = subset.drop_duplicates(subset=['nome'])['famiglia'].value_counts().reset_index()
    report.columns = ['Famiglia', 'Numero_Individui']

    # Salvataggio su file
    file_name = f'report_{circle_name.lower().replace(" ", "_")}.csv'
    report.to_csv(file_name, index=False)
    print(f"File creato: {file_name}")
    return report

# Generazione report per ogni cerchio pertinente
report_c0 = generate_and_save_report(cerchio_0, df_consiglio_savi, "Cerchio_0_Aristocrazia")
report_c2 = generate_and_save_report(cerchio_2, df_consiglio_anziani, "Cerchio_2_Elite_Savi")
report_c3 = generate_and_save_report(cerchio_3, df_consiglio_anziani, "Cerchio_3_Rete_Familiare")
report_c4 = generate_and_save_report(cerchio_4, df_consiglio_anziani, "Cerchio_4_Nuovi_Attori")

# Visualizzazione tabelle (anteprima prime 20 righe)
print("\n--- ANTEPRIMA: FAMIGLIE RETE FAMILIARE (C3) ---")
display(report_c3.head(20))

print("\n--- ANTEPRIMA: NUOVE FAMIGLIE (C4) ---")
display(report_c4.head(20))

"""### Focus sul Cerchio 1 e Prompt per Modelli Esterni
In questa sezione finale, isoliamo il Cerchio 1 come caso di studio della separazione dei poteri e generiamo il riepilogo per utilizzi futuri.
"""

import pandas as pd

# Definizione esplicita del Cerchio 1 (Nobili in entrambi i consigli)
# Utilizziamo il mapping fuzzy per identificare i match tra nobili savi e anziani
c1_individui = [ns for ns in cerchio_0 if ns in mapping_fuzzy]

print(f"--- ANALISI SPECIFICA CERCHIO 1 ---")
print(f"Individui identificati: {len(c1_individui)}")
if len(c1_individui) > 0:
    display(df_consiglio_savi[df_consiglio_savi['nome'].isin(c1_individui)][['nome', 'famiglia']])
else:
    print("Confermato: Nessuna sovrapposizione tra Aristocrazia e Consiglio degli Anziani.")

# Generazione del Prompt/Context per altri LLM
prompt_context = f"""
### CONTESTO DI ANALISI: POTERE POLITICO PISA XIV SECOLO

**Descrizione del Progetto:**
Analisi quantitativa dei rapporti di potere tra il Consiglio dei Savi (Elite decisionale) e il Consiglio degli Anziani (Organo amministrativo) basata su 2.954 individui unici.

**Struttura dei Cerchi di Potere:**
- **Cerchio 0 (Aristocrazia):** {len(cerchio_0_fuzzy)} individui. Nobili presenti solo nei Savi.
- **Cerchio 1 (Nobiltà Istituzionale):** {len(c1_individui)} individui. Nobili presenti in entrambi i consigli (caso raro/nullo).
- **Cerchio 2 (Elite Ponte):** {len(cerchio_2_fuzzy)} individui. Uomini non nobili presenti in entrambi i consigli (es. Gambacorta, Alliata).
- **Cerchio 3 (Rete delle Consorterie):** {len(cerchio_3_fuzzy)} individui. Anziani che non siedono nei Savi ma appartengono alle stesse famiglie del Cerchio 2.
- **Cerchio 4 (Uomini Nuovi):** {len(cerchio_4_fuzzy)} individui. Base politica senza legami familiari con l'elite dei Savi.

**Risultati Statistici:**
- Egemonia familiare: Il {perc_c3:.1f}% degli Anziani legati all'elite appartiene a una rete consorterile (C3).
- Famiglie Dominanti: Alliata (37), Bonconti (25), Grasso (22), Gambacorta (17).

**Utilizzo:** Questo contesto serve per analizzare la mobilità sociale e la stabilità delle istituzioni medievali.
"""

with open('contesto_analisi_pisa.md', 'w') as f:
    f.write(prompt_context)

print("\n[OK] File 'contesto_analisi_pisa.md' generato per l'uso come prompt.")

"""#### Testo del Prompt generato:
Puoi copiare il contenuto qui sotto per istruire altri modelli AI sull'analisi corrente.
"""

print(prompt_context)

